version: "3.7"
services:
  nsqlookupd:
    image: nsqio/nsq:v1.1.0
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - internal

  nsqd:
    image: nsqio/nsq:v1.1.0
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - internal

  nsqadmin:
    image: nsqio/nsq:v1.1.0
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - internal

  php:
    build:
      context: ./docker/images/php
    image: php:latest
    restart: "no"
    user: ${CURRENT_UID}
    tty: true
    volumes:
      - .:/var/www/html:rw
      - ./docker/images/php/php.dev.ini:/usr/local/etc/php/php.ini
      - ./docker/images/php/nsq.so:/usr/local/lib/php/extensions/no-debug-non-zts-20180731/nsq.so
    networks:
      - internal

networks:
  internal:
